spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost//Users/leekyoungchang/Desktop/Study/Computer/github/toyproject/db/springandaws;MODE=MYSQL
#    username: sa
#    password: 1234
#    driver-class-name: org.h2.Driver

  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb

  profiles:
    include:
      - oauth

  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  h2:
    console:
      enabled: true

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: test
#            client-secret: test
#            scope: profile, email

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace